name: Gradle Version Run Name

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  get-gradle-version:
    runs-on: ubuntu-latest
    outputs:
      gradle_version: ${{ steps.extract-version.outputs.gradle_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Gradle Version
        id: extract-version
        run: |
          GRADLE_VERSION=$(grep '^gradle_version=' gradle.properties | cut -d'=' -f2 || echo "")
          if [[ -z "$GRADLE_VERSION" ]]; then
            GRADLE_VERSION="1.0.0"
          fi
          echo "Gradle version: $GRADLE_VERSION"
          echo "gradle_version=$GRADLE_VERSION" >> "$GITHUB_OUTPUT"

  update-run-name:
    needs: get-gradle-version
    runs-on: ubuntu-latest
    steps:
      - name: Set Workflow Run Name Dynamically
        run: echo "GITHUB_RUN_NAME=Gradle Build - ${{ needs.get-gradle-version.outputs.gradle_version }}" >> $GITHUB_ENV
