name: "Prepare Action"
description: "Extract build version and application name from build.properties"

outputs:
  buildVersion:
    description: "Build Version"
    value: ${{ steps.extract.outputs.buildVersion }}
  applicationName:
    description: "Application Name"
    value: ${{ steps.extract.outputs.applicationName }}

runs:
  using: "composite"
  steps:
     - name: Checkout Code
       uses: actions/checkout@v3
       
     - name: Extract Build Properties
       id: extract
       shell: bash
       run: |
        buildVersion=$(grep 'artifact_version=' build.properties | cut -d '=' -f2)
        applicationName=$(grep 'artifact_name=' build.properties | cut -d '=' -f2)
        echo "buildVersion=$buildVersion" >> $GITHUB_ENV
        echo "applicationName=$applicationName" >> $GITHUB_ENV
        echo "::set-output name=buildVersion::$buildVersion"
        echo "::set-output name=applicationName::$applicationName"
