name: Merge Helm Values

on:
  push:
    branches:
      - master
    
  pull_request:
    branches:
      - master
      

jobs:
  merge-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run merge script
        run: python scripts/merge_helm_values.py
      - name: Debug - List all files in repo
        run: ls -R /home/runner/work/actions-demo/

      - name: Display Merged Files
        run: |
          echo "📂 Listing merged files:"
          ls -l cicd/charts/merge-values-*.yml

          echo "📜 Merged File Contents:"
          for file in cicd/charts/merge-values-*.yml; do
            echo "🔹 Merged File: $file"
            cat "$file"
            echo "-------------------------------------"
          done