name: Merge Helm Values

on:
  push:
    branches:
      - master
    
  pull_request:
    branches:
      - master
      

jobs:
  merge-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run merge script
        run: python scripts/merge_helm_values.py
      - name: Debug - List all files in repo
        run: ls -R /home/runner/work/actions-demo/

      - name: Display merged YAML files
        run: cat cicd/merge-values-*.yml || echo "❌ No merged files found"